JPERF-715: Improve assertion error in `JstatSupport`
Before:
```
java.lang.StringIndexOutOfBoundsException: String index out of range: -27
```

After:
```
java.lang.AssertionError: [length of ]
Expecting:
<0>
to be greater than:
<26>
```

So it seems the jstat log is sometimes empty.